# Generated by Django 5.2.7 on 2026-02-23 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityinsight',
            options={},
        ),
        migrations.CreateModel(
            name='SleepInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weekly_total_hours', models.FloatField(default=0)),
                ('weekly_avg_hours', models.FloatField(default=0)),
                ('weekly_avg_quality', models.FloatField(default=0)),
                ('hours_change_percentage', models.FloatField(default=0)),
                ('quality_change_percentage', models.FloatField(default=0)),
                ('recommendations', models.JSONField(default=list)),
                ('trend', models.CharField(choices=[('improving', 'في تحسن'), ('declining', 'في تراجع'), ('stable', 'مستقر'), ('insufficient_data', 'بيانات غير كافية')], default='insufficient_data', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
