# Generated by Django 5.2.7 on 2026-02-24 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_activityinsight_options_sleepinsight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_habits', models.IntegerField(default=0)),
                ('completed_today', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('top_habits', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('trend', models.CharField(default='insufficient_data', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MoodInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_days', models.IntegerField(default=0)),
                ('most_common_mood', models.CharField(default='', max_length=20)),
                ('mood_distribution', models.JSONField(default=dict)),
                ('mood_patterns', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('trend', models.CharField(default='insufficient_data', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
