# Generated by Django 5.2.7 on 2026-02-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_habitinsight_moodinsight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_meals', models.IntegerField(default=0)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('avg_calories', models.FloatField(default=0)),
                ('avg_protein', models.FloatField(default=0)),
                ('avg_carbs', models.FloatField(default=0)),
                ('avg_fat', models.FloatField(default=0)),
                ('meal_distribution', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('trend', models.CharField(default='insufficient_data', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
