# Generated by Django 5.2.7 on 2026-04-26 12:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رمز NDC')),
                ('brand_name', models.CharField(max_length=500, verbose_name='الاسم التجاري')),
                ('generic_name', models.CharField(blank=True, max_length=500, verbose_name='الاسم العلمي')),
                ('manufacturer', models.CharField(blank=True, max_length=500, verbose_name='الشركة المصنعة')),
                ('dosage_form', models.CharField(blank=True, max_length=200, verbose_name='شكل الجرعة')),
                ('route', models.CharField(blank=True, max_length=200, verbose_name='طريقة الاستخدام')),
                ('strength', models.CharField(blank=True, max_length=200, verbose_name='التركيز')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10, null=True, verbose_name='النوع')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='رقم الهاتف')),
                ('initial_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الوزن الأولي (كجم)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الطول (سم)')),
                ('occupation_status', models.CharField(choices=[('Student', 'طالب'), ('Full-Time', 'موظف بدوام كامل'), ('Freelancer', 'عمل حر'), ('Other', 'أخرى')], default='Other', max_length=50, verbose_name='الوضع الوظيفي/الأكاديمي')),
                ('health_goal', models.CharField(blank=True, choices=[('loss', 'خسارة وزن'), ('gain', 'زيادة وزن'), ('maintain', 'تثبيت الوزن')], max_length=20, null=True, verbose_name='الهدف الصحي')),
                ('activity_level', models.CharField(blank=True, choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], max_length=20, null=True, verbose_name='مستوى النشاط')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'المستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الإنجاز')),
                ('description', models.TextField(verbose_name='وصف الإنجاز')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='الأيقونة')),
                ('achieved_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنجاز')),
                ('category', models.CharField(choices=[('streak', 'تتابع'), ('activity', 'نشاط'), ('weight', 'وزن'), ('sleep', 'نوم'), ('habit', 'عادة'), ('special', 'خاص')], default='special', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إنجاز',
                'verbose_name_plural': 'الإنجازات',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الرسالة')),
                ('sender', models.CharField(choices=[('User', 'مستخدم'), ('Bot', 'روبوت')], max_length=10, verbose_name='المرسل')),
                ('message_text', models.TextField(verbose_name='نص الرسالة')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='درجة تحليل المشاعر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل الدردشة',
                'verbose_name_plural': 'سجلات الدردشة',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HabitDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العادة')),
                ('description', models.TextField(verbose_name='وصف العادة والهدف منها')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('frequency', models.CharField(choices=[('Daily', 'يومي'), ('Weekly', 'أسبوعي'), ('Monthly', 'شهري')], default='Daily', max_length=20, verbose_name='تكرار العادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='القيمة المستهدفة')),
                ('target_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='وحدة القياس (مثلاً: لتر، دقيقة)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_definitions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعريف العادة',
                'verbose_name_plural': 'تعريفات العادات',
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الهدف')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='القيمة المستهدفة (مثلاً: 65.0)')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='القيمة الحالية (للتتبع)')),
                ('unit', models.CharField(max_length=20, verbose_name='وحدة القياس (كجم، سم، إلخ)')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('target_date', models.DateField(verbose_name='تاريخ الانتهاء المستهدف')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='هل تم تحقيق الهدف؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'هدف صحي',
                'verbose_name_plural': 'الأهداف الصحية',
            },
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت التسجيل')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الوزن (كجم)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='معدل ضربات القلب (BPM)')),
                ('systolic_pressure', models.IntegerField(blank=True, null=True, verbose_name='الضغط الانقباضي')),
                ('diastolic_pressure', models.IntegerField(blank=True, null=True, verbose_name='الضغط الانبساطي')),
                ('spo2', models.IntegerField(blank=True, null=True, verbose_name='نسبة الأكسجين في الدم (SpO2%)')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='سكر الدم (mg/dL)')),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='درجة حرارة الجسم (C°)')),
                ('pulse', models.IntegerField(blank=True, null=True, verbose_name='النبض (Pulse)')),
                ('respiration_rate', models.IntegerField(blank=True, null=True, verbose_name='معدل التنفس ( breaths/min)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'القياسات الحيوية',
                'verbose_name_plural': 'سجلات القياسات الحيوية',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'فطور'), ('Lunch', 'غداء'), ('Dinner', 'عشاء'), ('Snack', 'وجبة خفيفة'), ('Other', 'أخرى')], max_length=20, verbose_name='نوع الوجبة')),
                ('meal_time', models.DateTimeField(verbose_name='تاريخ ووقت الوجبة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('ingredients', models.JSONField(default=list, verbose_name='المكونات')),
                ('total_calories', models.IntegerField(default=0, verbose_name='إجمالي السعرات')),
                ('total_protein', models.FloatField(default=0, verbose_name='إجمالي البروتين')),
                ('total_carbs', models.FloatField(default=0, verbose_name='إجمالي الكربوهيدرات')),
                ('total_fat', models.FloatField(default=0, verbose_name='إجمالي الدهون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الوجبة',
                'verbose_name_plural': 'الوجبات',
                'ordering': ['-meal_time'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المكون الغذائي')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='الكمية')),
                ('unit', models.CharField(max_length=20, verbose_name='وحدة القياس (جرام، مل، قطعة)')),
                ('calories', models.IntegerField(verbose_name='السعرات الحرارية')),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='البروتين (غ)')),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الكربوهيدرات (غ)')),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدهون (غ)')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='main.meal', verbose_name='الوجبة التابع لها')),
            ],
            options={
                'verbose_name': 'مكون غذائي',
                'verbose_name_plural': 'المكونات الغذائية',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='نوع الحدث')),
                ('event_date', models.DateField(verbose_name='تاريخ وقوع الحدث')),
                ('details', models.TextField(verbose_name='وصف تفصيلي للحدث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل طبي',
                'verbose_name_plural': 'السجلات الطبية',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Excellent', 'ممتاز'), ('Good', 'جيد'), ('Neutral', 'محايد'), ('Stressed', 'مرهق/مجهد'), ('Anxious', 'قلق'), ('Sad', 'حزين')], max_length=20, verbose_name='الحالة المزاجية المسجلة')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('factors', models.TextField(blank=True, null=True, verbose_name='العوامل المؤثرة (اختياري)')),
                ('text_entry', models.TextField(blank=True, null=True, verbose_name='إدخال نصي حر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل الحالة المزاجية',
                'verbose_name_plural': 'سجلات الحالة المزاجية',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50, verbose_name='نوع النشاط')),
                ('duration_minutes', models.IntegerField(verbose_name='المدة (دقيقة)')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='المسافة (كم)')),
                ('calories_burned', models.IntegerField(blank=True, null=True, verbose_name='السعرات المحروقة')),
                ('start_time', models.DateTimeField(verbose_name='وقت البداية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'النشاط البدني',
                'verbose_name_plural': 'الأنشطة البدنية',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=50, verbose_name='نوع التوصية')),
                ('content', models.TextField(verbose_name='نص التوصية/الإجراء المقترح')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت التوليد')),
                ('is_actioned', models.BooleanField(default=False, verbose_name='هل تم اتخاذ إجراء؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توصية ذكية',
                'verbose_name_plural': 'التوصيات الذكية',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان التذكير')),
                ('reminder_type', models.CharField(choices=[('medication', 'دواء'), ('habit', 'عادة'), ('water', 'ماء'), ('meal', 'وجبة'), ('sleep', 'نوم'), ('general', 'عام')], default='general', max_length=20)),
                ('reminder_time', models.TimeField(verbose_name='وقت التذكير')),
                ('reminder_days', models.JSONField(default=list, verbose_name='أيام التكرار (0=الأحد, 6=السبت)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='معرف العنصر المرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تذكير',
                'verbose_name_plural': 'التذكيرات',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_start', models.DateTimeField(verbose_name='وقت بداية النوم')),
                ('sleep_end', models.DateTimeField(verbose_name='وقت الاستيقاظ')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='المدة الكلية (بالساعة)')),
                ('quality_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='تقييم الجودة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات/أحلام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النوم',
                'verbose_name_plural': 'سجلات النوم',
                'ordering': ['-sleep_start'],
            },
        ),
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='الجرعة')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='التكرار')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='وقت التذكير')),
                ('reminder_days', models.CharField(blank=True, max_length=50, verbose_name='أيام التذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medications', to='main.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دواء المستخدم',
                'verbose_name_plural': 'أدوية المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحالة المزمنة')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التشخيص')),
                ('is_active', models.BooleanField(default=True, verbose_name='هل الحالة نشطة حالياً؟')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='الأدوية الحالية المتعلقة بالحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_conditions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مرض مزمن',
                'verbose_name_plural': 'الأمراض المزمنة',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('temperature', models.FloatField(verbose_name='درجة الحرارة')),
                ('weather_condition', models.CharField(max_length=100, verbose_name='حالة الطقس')),
                ('mood_at_recording', models.CharField(blank=True, max_length=50, null=True, verbose_name='الحالة المزاجية المسجلة في هذا الوقت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_data', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'البيانات البيئية',
                'verbose_name_plural': 'البيانات البيئية',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='تاريخ التسجيل')),
                ('is_completed', models.BooleanField(default=False, verbose_name='هل تم إنجاز العادة؟')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='القيمة الفعلية المُنجزة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإنجاز')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.habitdefinition', verbose_name='التعريف المرتبط')),
            ],
            options={
                'verbose_name': 'سجل عادة',
                'verbose_name_plural': 'سجلات العادات',
                'ordering': ['-log_date'],
                'unique_together': {('habit', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('health', 'صحي'), ('nutrition', 'تغذوي'), ('sleep', 'نوم'), ('mood', 'مزاج'), ('habit', 'عادة'), ('alert', 'تنبيه'), ('reminder', 'تذكير'), ('achievement', 'إنجاز'), ('tip', 'نصيحة')], default='alert', max_length=20, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('icon', models.CharField(default='🔔', max_length=10, verbose_name='الأيقونة')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الإجراء')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الإجراء')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='اقتراحات')),
                ('is_read', models.BooleanField(default=False, verbose_name='هل تم قراءة الإشعار؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف؟')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار النظام',
                'verbose_name_plural': 'إشعارات النظام',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', '-sent_at'], name='main_notifi_user_id_39dc89_idx'), models.Index(fields=['user', 'is_read'], name='main_notifi_user_id_844422_idx')],
            },
        ),
    ]
