# Generated by Django 5.2.7 on 2026-05-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='extracted_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='الأمراض المستخرجة (JSON)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'صورة'), ('unknown', 'غير معروف')], default='unknown', max_length=20, verbose_name='نوع الملف'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/%Y/%m/%d/', verbose_name='الملف المرفق (PDF/صورة)'),
        ),
    ]
